FROM ghcr.io/pnpm/pnpm:11 AS base
RUN pnpm runtime set node 22 -g
WORKDIR /app
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile
COPY . .
RUN pnpm build

FROM base AS migrate
CMD ["pnpm", "db:migrate"]

FROM base AS app
RUN pnpm install --frozen-lockfile --prod
CMD ["pnpm", "start"]
